services:
  web:
    container_name: rooster-web
    image: 495236579960.dkr.ecr.eu-central-1.amazonaws.com/roosterlive/django:${IMAGE_TAG}
    env_file:
      - /opt/rooster/app/.env
    environment:
      - PORT=8000
      - WORKERS=3
      - TIMEOUT=60
    expose:
      - "8000"
    depends_on:
      - redis
      - pgbouncer
    restart: unless-stopped

  celery:
    container_name: rooster-celery
    image: 495236579960.dkr.ecr.eu-central-1.amazonaws.com/roosterlive/django:${IMAGE_TAG}
    command: celery -A rooster_site worker -l INFO -Q mail,default,push -Ofair --concurrency=2 --max-tasks-per-child=100
    env_file:
      - /opt/rooster/app/.env
    depends_on:
      - redis
      - pgbouncer
    restart: unless-stopped

  celery-beat:
    container_name: rooster-celery-beat
    image: 495236579960.dkr.ecr.eu-central-1.amazonaws.com/roosterlive/django:${IMAGE_TAG}
    command: celery -A rooster_site beat -l INFO --pidfile= --schedule=/var/run/celery/celerybeat-schedule
    env_file:
      - /opt/rooster/app/.env
    depends_on:
      - redis
      - pgbouncer
    volumes:
      - celerybeat_data:/var/run/celery
    restart: unless-stopped

  redis:
    container_name: rooster-redis
    image: redis:7-alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
    restart: unless-stopped

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: rooster-pgbouncer
    env_file:
      - /opt/rooster/app/.env
    environment:
      LISTEN_PORT: 6432
      AUTH_TYPE: scram-sha-256
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 20
    expose:
      - "6432"
    restart: unless-stopped

  nginx:
    container_name: rooster-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  redis_data:
  celerybeat_data: