name: build-and-deploy-bluegreen
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495236579960:role/Github-deploy
          aws-region: eu-central-1

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (ARM64) with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/roosterlive/django:${{ github.sha }}
            ${{ steps.ecr.outputs.registry }}/roosterlive/django:cache
          cache-from: |
            type=gha,scope=roosterlive-django
            type=registry,ref=${{ steps.ecr.outputs.registry }}/roosterlive/django:cache
          cache-to: |
            type=gha,mode=max,scope=roosterlive-django
            type=registry,ref=${{ steps.ecr.outputs.registry }}/roosterlive/django:cache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Deploy via SSM (blue/green)
        run: |
          aws ssm send-command \
            --instance-ids "i-03368036882d6565f" \
            --document-name "AWS-RunShellScript" \
            --parameters commands=["/opt/rooster/app/deploy_bluegreen_repo.sh ${{ github.sha }} https://github.com/SemdeGroot/RoosterLive.git"] \
            --comment "Blue/green deploy ${{ github.sha }}"